"""add_teacher_qualification_fields

Revision ID: b6852c0913a4
Revises: 849155937fba
Create Date: 2026-06-26 14:50:48.723340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6852c0913a4'
down_revision: Union[str, None] = '849155937fba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('real_name', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('school_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('credential_code', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('credential_image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credential_image_url')
    op.drop_column('users', 'credential_code')
    op.drop_column('users', 'school_name')
    op.drop_column('users', 'real_name')
    # ### end Alembic commands ###
