"""add_unique_constraints

Revision ID: cebd28e41249
Revises: 4938543fe9cc
Create Date: 2026-05-27 23:33:46.492524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cebd28e41249'
down_revision: Union[str, None] = '4938543fe9cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_class_textbook', 'class_textbooks', ['class_id', 'textbook_id'])
    op.create_unique_constraint('uq_student_class', 'student_classes', ['student_id', 'class_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_student_class', 'student_classes', type_='unique')
    op.drop_constraint('uq_class_textbook', 'class_textbooks', type_='unique')
    # ### end Alembic commands ###
